databases:
  - name: course-db          # free Postgres database
    plan: free               # (Hobby tier)

services:
  - type: web
    name: course-platform    # appears in Render dashboard
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn src.cfehome.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: course-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12

